name: CI
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v3.0.1
    - name: Setup JDK
      uses: actions/setup-java@19eeec562b37d29a1ad055b7de9c280bd0906d8d # v3.7.0
      with:
        distribution: corretto
        java-version: 8
    - name: Build and Test
      run: echo done
