name: CI
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v3.0.1
    - name: Setup JDK
      uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
      with:
        distribution: corretto
        java-version: 8
    - name: Build and Test
      run: echo done
